services:
  - type: web
    name: viveiro-comurg-backend
    env: node
    plan: free
    buildCommand: "cd backend && npm install"
    startCommand: "cd backend && node server.js"
    envVars:
      - key: SENDGRID_API_KEY
        sync: false
      - key: CONTACT_EMAIL
        sync: false

  - type: web
    name: viveiro-comurg-frontend
    env: node
    plan: free
    buildCommand: "cd front-end && npm install && npm run build"
    startCommand: "cd front-end && npm run preview -- --port 10000 --host 0.0.0.0"
    envVars:
      - key: VITE_API_URL
        value: "https://viveiro-comurg-backend.onrender.com"

